server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gb?serverTimezone=Asia/Seoul
    username: gb
    password: 1234

  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB

coolsms:
  api:
    key: NCS25G6A1FACZMHF
    secret: ANWHAYC8JXWP0M89KARI1ATUJUCPSWV3
    number: 01090455160

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml
